version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:

  db:
    image: postgres:12.4
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - "8000:8000"

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports: 
      - '80:80'
    depends_on:
      - db
      - web
    volumes:
      - static:/static/
      - media:/media/